version: '3'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./src/test/resources/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql